@startuml

skinparam ParticipantPadding 20
skinparam BoxPadding 50

box "External"
    participant "Ftp Client" as FC
end box
box "FTP 2 RabbitMQ"
    participant "Ftp Server" as FS
end box
box "RabbitMQ"
    participant "RabbitMQ broker" as RMQ
    participant "Data Exchange" as DE
    participant "Info Exchange" as IE
end box

== Initialization ==

FS -> RMQ: create Data Exchange
DE <- RMQ: create

FS -> RMQ: create Info Exchange
IE <- RMQ: create

== Repetition ==

FC -> FS: login with username and password
FC <- FS: ok

FC -> FS: change directory to /a/b/c
FC <- FS: ok

FC -> FS: put_file abc.txt with content
FC <- FS: ok

FS -> DE: posts raw data <content>

FS -> IE: post info about content (filename, dir, hash)

@enduml
